# Generated by Django 3.1.3 on 2020-12-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('Puntos', models.IntegerField()),
                ('Wins', models.IntegerField()),
                ('Losses', models.IntegerField()),
                ('Diff', models.IntegerField()),
            ],
        ),
    ]
